In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
movies = pd.read_csv(r"C:\tmdb_5000_movies.csv")
#credits = pd.read_csv("C:\tmdb_5000_credits.csv")

In [3]:
credits = pd.read_csv(r"C:\tmdb_5000_credits.csv")

In [4]:
movies = movies.merge(credits,on='title')

In [5]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [6]:
movies.head(5)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [8]:
movies.dropna(inplace=True)

In [9]:
import ast

In [10]:
movies.iloc[0,:].genres 

# Note that it is a string value not a list 
# So our task will be to first convert this string to list than operatew on it

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [12]:
movies['genres'] = movies['genres'].apply(convert)
movies.head(5)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head(5)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
def convert3(obj):
  L = []
  counter=0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [15]:
movies['cast'] = movies['cast'].apply(convert3)
movies.head(5)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [17]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [18]:
movies['overview'] = movies['overview'].apply(lambda x : x.split())
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [19]:
movies['genres'] = movies['genres'].apply(lambda x : [i.replace(" ","") for i in x])
movies['genres']

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [20]:
movies['cast'] = movies['cast'].apply(lambda x : [i.replace(" ","") for i in x])
movies['cast']

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LéaSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishé, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4806, dtype: object

In [21]:
movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x : [i.replace(" ","") for i in x])

In [22]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head(5)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [23]:
new_df = movies[['movie_id' , 'title' , 'tags']]
new_df.head(5)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [1]:
import nltk

In [2]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [6]:
ps.stem('activities')

'activ'

In [26]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [27]:
new_df['tags'] = new_df['tags'].apply(stem)

AttributeError: 'list' object has no attribute 'split'

In [28]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))
new_df['tags'][0]

C:\Users\VEDANT~1\AppData\Local\Temp/ipykernel_1716/2691087867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [29]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())
new_df['tags'][0]

C:\Users\VEDANT~1\AppData\Local\Temp/ipykernel_1716/4110224503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [31]:
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alpha',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'automobileracing',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'bad',
 'badly',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlove',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridge',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brooklyn',
 'brooks',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'chazzpalminteri',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cindy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'confederate',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 ...]

In [33]:
from sklearn.metrics.pairwise import cosine_similarity 
similarity = cosine_similarity(vectors)

In [34]:
similarity

array([[1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
        0.        ],
       [0.08964215, 1.        , 0.0625    , ..., 0.02635231, 0.        ,
        0.        ],
       [0.05976143, 0.0625    , 1.        , ..., 0.02635231, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02635231, ..., 1.        , 0.0745356 ,
        0.04836508],
       [0.02817181, 0.        , 0.        , ..., 0.0745356 , 1.        ,
        0.05407381],
       [0.        , 0.        , 0.        , ..., 0.04836508, 0.05407381,
        1.        ]])

In [35]:
dist = similarity[new_df.index[3]]

sorted(list(enumerate(dist)),reverse = True,key = lambda x:x[1])

[(3, 0.999999999999999),
 (65, 0.4239113759983974),
 (119, 0.3535533905932739),
 (1363, 0.3466876226407682),
 (428, 0.3333333333333334),
 (1362, 0.32274861218395146),
 (299, 0.31675175604649874),
 (210, 0.28676966733820225),
 (2513, 0.23112508176051214),
 (9, 0.230967442718578),
 (3860, 0.22680460581325726),
 (3595, 0.223606797749979),
 (590, 0.22116293423234573),
 (3825, 0.21821789023599236),
 (1670, 0.2057377999494559),
 (3948, 0.19888932104393253),
 (2390, 0.1944444444444445),
 (238, 0.19302200804786204),
 (1990, 0.17895849739771977),
 (3720, 0.1776672636296754),
 (4071, 0.1776672636296754),
 (4641, 0.1767766952966369),
 (3879, 0.17568209223157663),
 (1494, 0.17201561551404668),
 (2246, 0.17190354104313227),
 (4231, 0.17149858514250887),
 (4412, 0.1666666666666667),
 (761, 0.16666666666666666),
 (1184, 0.16666666666666666),
 (2280, 0.16412198797244365),
 (3024, 0.16412198797244365),
 (3310, 0.16412198797244365),
 (3077, 0.16222142113076254),
 (884, 0.15936381457791918),
 (2644, 0.15936381457791918),
 (553, 0.1587632240692801),
 (1054, 0.1587632240692801),
 (3863, 0.15811388300841897),
 (408, 0.15430334996209194),
 (2342, 0.15430334996209194),
 (1404, 0.153190838336343),
 (1250, 0.15294382258037453),
 (1437, 0.15214515486254612),
 (3941, 0.15214515486254612),
 (1149, 0.15061601901917734),
 (717, 0.14852213144650114),
 (1746, 0.1481668148335556),
 (1633, 0.14724203476646205),
 (1650, 0.14569287935358965),
 (1180, 0.14547859349066158),
 (1233, 0.14547859349066158),
 (777, 0.14433756729740646),
 (4652, 0.14433756729740646),
 (2052, 0.14377703093791788),
 (4341, 0.14360673947588823),
 (212, 0.1421338109037403),
 (286, 0.1417366773784602),
 (283, 0.14147911460452758),
 (2160, 0.14147911460452756),
 (2981, 0.14142135623730953),
 (782, 0.1405456737852613),
 (116, 0.13944333775567927),
 (1046, 0.13944333775567927),
 (3039, 0.13900960937138318),
 (1521, 0.13888888888888892),
 (2394, 0.13888888888888892),
 (31, 0.13608276348795437),
 (4702, 0.1356222452011225),
 (1424, 0.1351845176089688),
 (3972, 0.1351845176089688),
 (739, 0.13518451760896877),
 (1256, 0.13483997249264845),
 (1205, 0.13382584475782772),
 (1181, 0.1336306209562122),
 (4148, 0.1336306209562122),
 (4253, 0.1336306209562122),
 (209, 0.13176156917368248),
 (3840, 0.13176156917368248),
 (879, 0.13130643285972257),
 (737, 0.13043729868748777),
 (2014, 0.13043729868748777),
 (1900, 0.13043729868748774),
 (2404, 0.12950478164763524),
 (405, 0.12909944487358058),
 (1733, 0.1288367804206543),
 (3066, 0.1288367804206543),
 (3261, 0.12858612496840996),
 (3336, 0.12858612496840996),
 (873, 0.12830005981991685),
 (2728, 0.12830005981991685),
 (2261, 0.1270001270001905),
 (1352, 0.12598815766974245),
 (1879, 0.12598815766974242),
 (3363, 0.12598815766974242),
 (3733, 0.12598815766974242),
 (3829, 0.12598815766974242),
 (2199, 0.1256297269074015),
 (2928, 0.1256297269074015),
 (4173, 0.125),
 (978, 0.12499999999999999),
 (1199, 0.12309149097933277),
 (2044, 0.12309149097933277),
 (1038, 0.12297746456210365),
 (2919, 0.12286829679574764),
 (4357, 0.12286829679574764),
 (139, 0.12171612389003691),
 (611, 0.12163340819996028),
 (1748, 0.12163340819996028),
 (3673, 0.12126781251816648),
 (695, 0.12028130608117206),
 (1944, 0.12028130608117206),
 (4408, 0.12028130608117206),
 (160, 0.12009611535381534),
 (606, 0.11952286093343936),
 (376, 0.11907241805196006),
 (1418, 0.11785113019775795),
 (224, 0.11785113019775793),
 (442, 0.11785113019775793),
 (866, 0.11785113019775793),
 (2310, 0.11785113019775793),
 (3303, 0.11785113019775793),
 (370, 0.11785113019775792),
 (4344, 0.11785113019775792),
 (4330, 0.11694106924093726),
 (1087, 0.11666666666666667),
 (1592, 0.1162476387438193),
 (2549, 0.1160517706371319),
 (615, 0.1155625408802561),
 (3834, 0.1155625408802561),
 (4667, 0.1155625408802561),
 (4775, 0.1155625408802561),
 (1061, 0.1147078669352809),
 (189, 0.1143323900950059),
 (1360, 0.1143323900950059),
 (2297, 0.1143323900950059),
 (3308, 0.1143323900950059),
 (3420, 0.1143323900950059),
 (762, 0.11340230290662863),
 (4683, 0.11340230290662863),
 (2963, 0.11331668394168083),
 (807, 0.11322770341445959),
 (1248, 0.11322770341445958),
 (2276, 0.11322770341445958),
 (170, 0.11226255234242724),
 (377, 0.11226255234242724),
 (4133, 0.11226255234242724),
 (2592, 0.1118033988749895),
 (3675, 0.1118033988749895),
 (511, 0.1113588507968435),
 (3263, 0.1113588507968435),
 (818, 0.11135885079684349),
 (1425, 0.11135885079684349),
 (2041, 0.11135885079684349),
 (3549, 0.11135885079684349),
 (4505, 0.11135885079684349),
 (355, 0.11111111111111115),
 (808, 0.11111111111111115),
 (1476, 0.11111111111111115),
 (2259, 0.11111111111111115),
 (2551, 0.11111111111111115),
 (2961, 0.11111111111111115),
 (647, 0.11043152607484655),
 (3734, 0.10959932487023821),
 (1249, 0.10942202738310215),
 (1726, 0.10942202738310215),
 (3264, 0.10942202738310215),
 (1086, 0.10910894511799621),
 (1325, 0.1091089451179962),
 (342, 0.10886621079036346),
 (3599, 0.10832228060328025),
 (1236, 0.10814761408717503),
 (1624, 0.10814761408717503),
 (3982, 0.10814761408717502),
 (724, 0.10783277320343844),
 (1498, 0.10783277320343844),
 (282, 0.10758287072798382),
 (369, 0.10758287072798382),
 (3322, 0.10758287072798381),
 (1276, 0.10660035817780524),
 (1632, 0.10660035817780524),
 (2485, 0.10660035817780524),
 (468, 0.10583343916682543),
 (1485, 0.10583343916682543),
 (2559, 0.10583343916682543),
 (3301, 0.10583343916682543),
 (3511, 0.10583343916682543),
 (1268, 0.10540925533894599),
 (1090, 0.10540925533894598),
 (1544, 0.10540925533894598),
 (3875, 0.10540925533894598),
 (153, 0.10476975951561872),
 (97, 0.10425720702853739),
 (1146, 0.10425720702853739),
 (4105, 0.10425720702853739),
 (2879, 0.10416666666666666),
 (3647, 0.10416666666666666),
 (939, 0.10393492741038726),
 (2448, 0.1034867367608444),
 (674, 0.10314212462587936),
 (4399, 0.10314212462587935),
 (1541, 0.10311973892303819),
 (538, 0.10286889997472796),
 (1734, 0.10286889997472796),
 (2925, 0.10286889997472796),
 (3491, 0.10286889997472796),
 (3590, 0.10286889997472796),
 (1438, 0.10286889997472795),
 (3176, 0.10286889997472795),
 (449, 0.1025762424827773),
 (741, 0.1025762424827773),
 (1866, 0.1025762424827773),
 (2211, 0.1025762424827773),
 (1239, 0.1023234355858201),
 (4670, 0.1023234355858201),
 (30, 0.10206207261596578),
 (1272, 0.10206207261596578),
 (4572, 0.10206207261596578),
 (41, 0.10206207261596577),
 (215, 0.10206207261596577),
 (281, 0.10206207261596577),
 (574, 0.10206207261596577),
 (1463, 0.10206207261596577),
 (303, 0.10105651043180541),
 (437, 0.10105651043180541),
 (576, 0.10105651043180541),
 (1012, 0.10105651043180541),
 (1212, 0.10105651043180541),
 (4213, 0.10105651043180541),
 (1772, 0.10078464965115869),
 (56, 0.10050378152592121),
 (669, 0.10050378152592121),
 (1154, 0.10050378152592121),
 (2508, 0.10050378152592121),
 (2564, 0.10050378152592121),
 (3395, 0.10050378152592121),
 (3839, 0.10050378152592121),
 (4270, 0.10050378152592121),
 (351, 0.1),
 (1930, 0.1),
 (339, 0.09960238411119947),
 (854, 0.09960238411119947),
 (955, 0.09960238411119947),
 (1380, 0.09960238411119947),
 (1388, 0.09960238411119947),
 (1792, 0.09960238411119947),
 (2066, 0.09960238411119947),
 (29, 0.09901475429766744),
 (248, 0.09901475429766744),
 (425, 0.09901475429766743),
 (3330, 0.09901475429766743),
 (157, 0.09829463743659811),
 (668, 0.09829463743659811),
 (1085, 0.09829463743659811),
 (1092, 0.09829463743659811),
 (3170, 0.09829463743659811),
 (3297, 0.09829463743659811),
 (714, 0.09820927516479827),
 (1952, 0.09820927516479827),
 (3347, 0.09820927516479827),
 (4142, 0.09820927516479827),
 (58, 0.09805806756909204),
 (314, 0.09805806756909204),
 (1375, 0.09805806756909204),
 (1673, 0.09805806756909204),
 (2675, 0.09805806756909204),
 (3728, 0.09805806756909204),
 (3978, 0.09805806756909204),
 (4261, 0.09805806756909204),
 (4348, 0.09805806756909204),
 (4353, 0.09805806756909204),
 (2434, 0.0979044918012804),
 (82, 0.09687303228651607),
 (312, 0.09687303228651607),
 (632, 0.09687303228651607),
 (1764, 0.09687303228651607),
 (1771, 0.09687303228651607),
 (1961, 0.09687303228651607),
 (2638, 0.09687303228651607),
 (359, 0.09622504486493764),
 (920, 0.09622504486493764),
 (1055, 0.09622504486493764),
 (1306, 0.09622504486493764),
 (1669, 0.09622504486493764),
 (2100, 0.09622504486493764),
 (2496, 0.09622504486493764),
 (2532, 0.09622504486493764),
 (2661, 0.09622504486493764),
 (3421, 0.09622504486493764),
 (3674, 0.09622504486493764),
 (3791, 0.09622504486493764),
 (3946, 0.09622504486493764),
 (3973, 0.09622504486493764),
 (2032, 0.09589940926145842),
 (731, 0.09558988911273408),
 (1560, 0.09558988911273408),
 (2591, 0.09558988911273408),
 (3541, 0.09558988911273408),
 (252, 0.09534625892455925),
 (285, 0.09534625892455925),
 (694, 0.09534625892455924),
 (1462, 0.09534625892455924),
 (2422, 0.09534625892455924),
 (3326, 0.09534625892455924),
 (602, 0.09449111825230683),
 (774, 0.09449111825230681),
 (2480, 0.09449111825230681),
 (3130, 0.09449111825230681),
 (3159, 0.09449111825230681),
 (3510, 0.09449111825230681),
 (3996, 0.09449111825230681),
 (4737, 0.09449111825230681),
 (182, 0.09435641951204965),
 (958, 0.09435641951204965),
 (1367, 0.09435641951204965),
 (3206, 0.09435641951204965),
 (1607, 0.09428090415820635),
 (2283, 0.09428090415820635),
 (2741, 0.09428090415820635),
 (4200, 0.0936585811581694),
 (1136, 0.09335200560186732),
 (1013, 0.09316949906249125),
 (1108, 0.09316949906249125),
 (2655, 0.09316949906249125),
 (2828, 0.09316949906249125),
 (982, 0.09284766908852593),
 (736, 0.09245003270420488),
 (2615, 0.09245003270420488),
 (3692, 0.09245003270420488),
 (3857, 0.09245003270420488),
 (3933, 0.09245003270420488),
 (3968, 0.09245003270420488),
 (4491, 0.09245003270420488),
 (4579, 0.09245003270420488),
 (277, 0.09205746178983236),
 (324, 0.0920262717290388),
 (968, 0.0920262717290388),
 (1470, 0.0920262717290388),
 (2408, 0.0920262717290388),
 (3801, 0.0920262717290388),
 (4373, 0.09128709291752769),
 (1041, 0.09128709291752768),
 (1621, 0.09128709291752768),
 (4139, 0.09128709291752768),
 (529, 0.09092412093166351),
 (122, 0.0907218423253029),
 (941, 0.0907218423253029),
 (976, 0.0907218423253029),
 (1027, 0.0907218423253029),
 (1052, 0.0907218423253029),
 (1073, 0.0907218423253029),
 (1492, 0.0907218423253029),
 (2461, 0.0907218423253029),
 (3238, 0.0907218423253029),
 (4166, 0.0907218423253029),
 (607, 0.09053574604251854),
 (1898, 0.09053574604251854),
 (3731, 0.09053574604251854),
 (76, 0.0898606443361987),
 (1257, 0.0898606443361987),
 (1958, 0.0898606443361987),
 (1659, 0.08980265101338747),
 (236, 0.0890870806374748),
 (259, 0.0890870806374748),
 (983, 0.0890870806374748),
 (1079, 0.0890870806374748),
 (2786, 0.0890870806374748),
 (3078, 0.0890870806374748),
 (3116, 0.0890870806374748),
 (3544, 0.0890870806374748),
 (3745, 0.0890870806374748),
 (3766, 0.0890870806374748),
 (4613, 0.0890870806374748),
 (4781, 0.0890870806374748),
 (813, 0.0888336318148377),
 (919, 0.0888336318148377),
 (962, 0.0888336318148377),
 (1281, 0.0888336318148377),
 (1559, 0.0888336318148377),
 (3108, 0.0888336318148377),
 (3184, 0.0888336318148377),
 (3458, 0.0888336318148377),
 (1033, 0.08838834764831845),
 (2780, 0.08838834764831845),
 (2882, 0.08838834764831845),
 (3203, 0.08838834764831845),
 (3243, 0.08838834764831845),
 (3496, 0.08838834764831845),
 (4010, 0.08838834764831845),
 (4411, 0.08838834764831845),
 (4651, 0.08838834764831845),
 (4783, 0.08838834764831845),
 (528, 0.08784104611578832),
 (834, 0.08784104611578832),
 (1823, 0.08784104611578832),
 (2441, 0.08784104611578832),
 (3382, 0.08784104611578832),
 (4449, 0.08770580193070295),
 (242, 0.08753762190648172),
 (275, 0.08753762190648172),
 (977, 0.08753762190648172),
 (1004, 0.08753762190648172),
 (1834, 0.08753762190648172),
 (1850, 0.08753762190648172),
 (1903, 0.08753762190648172),
 (2348, 0.08753762190648172),
 (2405, 0.08753762190648172),
 (2552, 0.08753762190648172),
 (3114, 0.08753762190648172),
 (3902, 0.08753762190648172),
 (4575, 0.08753762190648172),
 (2056, 0.0868810058571145),
 (629, 0.08688100585711449),
 (1433, 0.08688100585711449),
 (1755, 0.08688100585711449),
 (2209, 0.08688100585711449),
 (2554, 0.08688100585711449),
 (4180, 0.08688100585711449),
 (415, 0.08647908694379515),
 (296, 0.08638684255813601),
 (72, 0.08606629658238706),
 (164, 0.08606629658238706),
 (844, 0.08606629658238706),
 (1253, 0.08606629658238706),
 (2266, 0.08606629658238706),
 (2824, 0.08606629658238706),
 (3468, 0.08606629658238706),
 (2153, 0.08595177052156613),
 (3522, 0.08595177052156613),
 (589, 0.08595177052156612),
 (850, 0.08574929257125442),
 (892, 0.08574929257125442),
 (1078, 0.08574929257125442),
 (2275, 0.08574929257125442),
 (2326, 0.08574929257125442),
 (2590, 0.08574929257125442),
 (3227, 0.08574929257125442),
 (3288, 0.08574929257125442),
 (4258, 0.08574929257125442),
 (421, 0.08505172717997148),
 (830, 0.08466675133346034),
 (1859, 0.08466675133346034),
 (3679, 0.08466675133346034),
 (3789, 0.08466675133346034),
 (3823, 0.08466675133346034),
 (3845, 0.08466675133346034),
 (4452, 0.08466675133346034),
 (950, 0.08451542547285167),
 (747, 0.08417937871268424),
 (1455, 0.08417937871268424),
 (2286, 0.08417937871268424),
 (3044, 0.08417937871268424),
 (3341, 0.08417937871268424),
 (4483, 0.08417937871268423),
 (205, 0.08333333333333336),
 (598, 0.08333333333333336),
 (967, 0.08333333333333336),
 (1393, 0.08333333333333336),
 (2869, 0.08333333333333336),
 (3047, 0.08333333333333336),
 (4130, 0.08333333333333336),
 (4463, 0.08333333333333336),
 (4557, 0.08333333333333336),
 (790, 0.08333333333333334),
 (985, 0.08333333333333334),
 (1197, 0.08333333333333334),
 (3648, 0.08333333333333334),
 (3700, 0.08333333333333334),
 (3740, 0.08333333333333334),
 (166, 0.08333333333333333),
 (198, 0.08333333333333333),
 (909, 0.08333333333333333),
 (1196, 0.08333333333333333),
 (1490, 0.08333333333333333),
 (2984, 0.08333333333333333),
 (3552, 0.08333333333333333),
 (4039, 0.08333333333333333),
 (4189, 0.08333333333333333),
 (4210, 0.08333333333333333),
 (1832, 0.0825122952480562),
 (2606, 0.0825122952480562),
 (1278, 0.08251229524805619),
 (280, 0.08206099398622184),
 (672, 0.08206099398622184),
 (2229, 0.08206099398622184),
 (2314, 0.08206099398622184),
 (2662, 0.08206099398622184),
 (3920, 0.08206099398622184),
 (469, 0.0817150563075767),
 (1435, 0.0817150563075767),
 (2213, 0.0817150563075767),
 (4751, 0.0817150563075767),
 (613, 0.08111071056538127),
 (627, 0.08111071056538127),
 (771, 0.08111071056538127),
 (995, 0.08111071056538127),
 (1672, 0.08111071056538127),
 (2136, 0.08111071056538127),
 (2338, 0.08111071056538127),
 (2621, 0.08111071056538127),
 (3088, 0.08111071056538127),
 (3398, 0.08111071056538127),
 (3413, 0.08111071056538127),
 (3627, 0.08111071056538127),
 (3644, 0.08111071056538127),
 (1777, 0.08094048852977202),
 (2069, 0.08094048852977202),
 (2256, 0.08094048852977202),
 (3298, 0.08094048852977202),
 (196, 0.08084520834544433),
 (508, 0.08084520834544433),
 (603, 0.08084520834544433),
 (690, 0.08084520834544433),
 (867, 0.08084520834544433),
 (965, 0.08084520834544433),
 (1161, 0.08084520834544433),
 (2183, 0.08084520834544433),
 (2446, 0.08084520834544433),
 (2921, 0.08084520834544433),
 (3557, 0.08084520834544433),
 (4167, 0.08084520834544433),
 (180, 0.08018753738744804),
 (1456, 0.08018753738744804),
 (26, 0.07968190728895957),
 (545, 0.07968190728895957),
 (2224, 0.07968190728895957),
 (2736, 0.07968190728895957),
 (2798, 0.07968190728895957),
 (3320, 0.07968190728895957),
 (3878, 0.07968190728895957),
 (4155, 0.07968190728895957),
 (4770, 0.07968190728895957),
 (586, 0.07945521577046603),
 (1122, 0.07945521577046603),
 (1992, 0.07945521577046603),
 (172, 0.07905694150420949),
 (570, 0.07905694150420949),
 (970, 0.07905694150420949),
 (1240, 0.07905694150420949),
 (1415, 0.07905694150420949),
 (1524, 0.07905694150420949),
 (1721, 0.07905694150420949),
 (1770, 0.07905694150420949),
 (2117, 0.07905694150420949),
 (2308, 0.07905694150420949),
 (3177, 0.07905694150420949),
 (3767, 0.07905694150420949),
 (3837, 0.07905694150420949),
 (4128, 0.07905694150420949),
 (4135, 0.07905694150420949),
 (4137, 0.07905694150420949),
 (4235, 0.07905694150420949),
 (4241, 0.07905694150420949),
 (4257, 0.07905694150420949),
 (4403, 0.07905694150420949),
 (3545, 0.07874259854358902),
 (24, 0.07856742013183862),
 (472, 0.07856742013183862),
 (2007, 0.07856742013183862),
 (2418, 0.07856742013183862),
 (3037, 0.07856742013183862),
 (3296, 0.07856742013183862),
 (3389, 0.07856742013183862),
 (3620, 0.07856742013183862),
 (3855, 0.07856742013183862),
 (4053, 0.07856742013183862),
 (654, 0.07804881763180785),
 (1497, 0.07804881763180785),
 (4117, 0.07804881763180785),
 (622, 0.07804881763180783),
 (821, 0.0776150525706333),
 (115, 0.07749842582921286),
 (500, 0.07749842582921286),
 (3284, 0.07749842582921286),
 (3451, 0.07749842582921286),
 (4374, 0.07749842582921286),
 (3596, 0.07737305757377161),
 (4077, 0.07737305757377161),
 (561, 0.07715167498104597),
 (1044, 0.07715167498104597),
 (1681, 0.07715167498104597),
 (2194, 0.07715167498104597),
 (2222, 0.07715167498104597),
 (2779, 0.07715167498104597),
 (2952, 0.07715167498104597),
 (3319, 0.07715167498104597),
 (3352, 0.07715167498104597),
 (3886, 0.07715167498104597),
 (3929, 0.07715167498104597),
 (4027, 0.07715167498104597),
 (4066, 0.07715167498104597),
 (4145, 0.07715167498104597),
 (4659, 0.07715167498104597),
 (4733, 0.07715167498104597),
 (246, 0.07671455149152696),
 (2612, 0.07671455149152696),
 (535, 0.07647191129018727),
 (849, 0.07647191129018727),
 (1204, 0.07647191129018727),
 (1341, 0.07647191129018727),
 (1454, 0.07647191129018727),
 (1602, 0.07647191129018727),
 (2799, 0.07647191129018727),
 (2820, 0.07647191129018727),
 (4095, 0.07647191129018727),
 (4288, 0.07647191129018727),
 (25, 0.07624928516630233),
 (1638, 0.07607257743127306),
 (4364, 0.07607257743127306),
 (4559, 0.07607257743127306),
 (2049, 0.07580980435789035),
 (2301, 0.07580980435789035),
 (988, 0.07548513560963972),
 (1208, 0.07548513560963972),
 (1235, 0.07548513560963972),
 (2201, 0.07548513560963972),
 (2409, 0.07548513560963972),
 (2527, 0.07548513560963972),
 (2902, 0.07548513560963972),
 (4230, 0.07548513560963972),
 (696, 0.07544645503543213),
 (1509, 0.07544645503543213),
 (267, 0.07537783614444091),
 (304, 0.07537783614444091),
 (476, 0.07537783614444091),
 (497, 0.07537783614444091),
 (826, 0.07537783614444091),
 (1049, 0.07537783614444091),
 (1152, 0.07537783614444091),
 (1156, 0.07537783614444091),
 (1335, 0.07537783614444091),
 (1400, 0.07537783614444091),
 (1594, 0.07537783614444091),
 (1666, 0.07537783614444091),
 (1787, 0.07537783614444091),
 (2174, 0.07537783614444091),
 (2584, 0.07537783614444091),
 (2837, 0.07537783614444091),
 (3004, 0.07537783614444091),
 (3213, 0.07537783614444091),
 (3533, 0.07537783614444091),
 (4198, 0.07537783614444091),
 (4228, 0.07537783614444091),
 (4324, 0.07537783614444091),
 (4479, 0.07537783614444091),
 (1639, 0.07483554251115622),
 (4169, 0.07483554251115622),
 (168, 0.074535599249993),
 (658, 0.074535599249993),
 (930, 0.074535599249993),
 (990, 0.074535599249993),
 (2352, 0.074535599249993),
 (2377, 0.074535599249993),
 (2432, 0.074535599249993),
 (3229, 0.074535599249993),
 (4453, 0.074535599249993),
 (4624, 0.074535599249993),
 (4633, 0.074535599249993),
 (755, 0.07423923386456233),
 (1641, 0.07423923386456233),
 (85, 0.07412493166611013),
 (308, 0.07372097807744858),
 (621, 0.07372097807744858),
 (716, 0.07372097807744858),
 (797, 0.07372097807744858),
 (991, 0.07372097807744858),
 (1242, 0.07372097807744858),
 (1423, 0.07372097807744858),
 (1899, 0.07372097807744858),
 (2067, 0.07372097807744858),
 (2218, 0.07372097807744858),
 (2228, 0.07372097807744858),
 (2271, 0.07372097807744858),
 (3092, 0.07372097807744858),
 (3211, 0.07372097807744858),
 (3224, 0.07372097807744858),
 (3901, 0.07372097807744858),
 (4104, 0.07372097807744858),
 (3583, 0.0736569563735987),
 (3942, 0.0736569563735987),

In [36]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distance = similarity[movie_index]
    movie_list = sorted(list(enumerate(distance)),reverse = True,key = lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [37]:
recommend('The Dark Knight Rises')

The Dark Knight
Batman Begins
Batman
Batman Returns
Batman

In [38]:
import pickle 

pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [41]:
new_ved = pd.DataFrame(new_df)
new_ved.head(5)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [39]:
pickle.dump(similarity,open('similarity.pkl','wb'))